# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-03 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20170724_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='author',
        ),
    ]
