# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsbk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qiushiarticle',
            name='url',
            field=models.URLField(default=1, verbose_name='\u6587\u7ae0\u8fde\u63a5'),
            preserve_default=False,
        ),
    ]
